my_set = set("test of set")
my_set3 = set("test of set for test")
my_set2 = my_set.copy()
print(my_set2)
print(len(my_set2))
print("s" in my_set2)
print("g" in my_set2)
print(my_set2 == my_set)
print(my_set2 == my_set3)
my_set2 = my_set2.union(my_set3)
print(my_set2)
my_set2 = my_set2.intersection(my_set)
print(my_set2)